Repository TheChance101/Honey-Mart-Android-Client, pull requests merged in 2023-08, with the labels that each got.

#246 Feature/owner update category
  core/data/src/main/java/org/the_chance/honeymart/data/repository/HoneyMartRepositoryImp.kt
  core/data/src/main/java/org/the_chance/honeymart/data/source/remote/network/HoneyMartService.kt
  core/data/src/main/java/org/the_chance/honeymart/data/source/remote/network/HoneyMartServiceImp.kt
  core/domain/src/main/java/org/the_chance/honeymart/domain/repository/HoneyMartRepository.kt
  core/domain/src/main/java/org/the_chance/honeymart/domain/usecase/UpdateCategoryUseCase.kt
  design_system/src/debug/res/drawable/icon_update_category.xml
  design_system/src/main/java/org/the_chance/honymart/ui/composables/HoneyOutlineButton.kt
  design_system/src/main/java/org/the_chance/honymart/ui/theme/Dimens.kt
  design_system/src/main/res/drawable/ic_adhesive_plaster.xml
  design_system/src/main/res/drawable/ic_airbuds.xml
  design_system/src/main/res/drawable/ic_book.xml
  design_system/src/main/res/drawable/ic_calculator.xml
  design_system/src/main/res/drawable/ic_case_round_minimalistic.xml
  design_system/src/main/res/drawable/ic_cat.xml
  design_system/src/main/res/drawable/ic_chandelier.xml
  design_system/src/main/res/drawable/ic_chef_hat.xml
  design_system/src/main/res/drawable/ic_confetti_minimalistic.xml
  design_system/src/main/res/drawable/ic_cup.xml
  design_system/src/main/res/drawable/ic_devices.xml
  design_system/src/main/res/drawable/ic_earth.xml
  design_system/src/main/res/drawable/ic_glasses.xml
  design_system/src/main/res/drawable/ic_laptop.xml
  design_system/src/main/res/drawable/ic_scissors.xml
  design_system/src/main/res/drawable/ic_sofa.xml
  design_system/src/main/res/drawable/ic_t_shirt.xml
  design_system/src/main/res/drawable/ic_telescope.xml
  design_system/src/main/res/drawable/ic_ufo.xml
  design_system/src/main/res/drawable/ic_umbrella.xml
  design_system/src/main/res/values/strings.xml
  owner/src/main/java/org/the_chance/honeymart/ui/MainActivity.kt
  owner/src/main/java/org/the_chance/honeymart/ui/components/FormHeader.kt
  owner/src/main/java/org/the_chance/honeymart/ui/components/FormTextField.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/AddProductInteractionListener.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/AddProductScreen.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/AddProductUiState.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/AddProductViewModel.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/components/AddImageButton.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/components/AddProductForm.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/components/ItemImageProduct.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/add_product/components/SelectedImagesGrid.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/update_category/UpdateCategoryInteractionListener.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/update_category/UpdateCategoryScreen.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/update_category/UpdateCategoryUiState.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/update_category/UpdateCategoryViewModel.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/update_category/components/CategoryIconItem.kt
Labels: feature

#284 fix/refactor-navigation-double-tap
  user/src/main/java/org/the_chance/honeymart/ui/MainActivity.kt
  user/src/main/java/org/the_chance/honeymart/ui/composables/NavigationHandler.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/authentication/AuthScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/cart/CartScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/category/CategoriesScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/home/HomeScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/login/LoginScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/markets/MarketsScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/order_details/OrderDetailsScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/orders/OrdersScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/product/ProductsScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/product_details/ProductDetailsScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/search/SearchScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/signup/SignupScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/wishlist/WishListScreen.kt
Labels: hotfix

#285 fixing cart price & search.
  user/src/main/java/org/the_chance/honeymart/ui/feature/cart/CartUiState.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/cart/CartViewModel.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/markets/MarketsScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/search/SearchScreen.kt
Labels: hotfix

#305 fix/bugs_user_cart_order
  design_system/src/main/java/org/the_chance/honymart/ui/composables/CustomeDialog.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/cart/CartViewModel.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/HomeSuccessScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/orders/OrderViewModel.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/product_details/ProductDetailsScreen.kt
Labels: hotfix

#308 Feature/owner profile
  core/data/src/main/java/org/the_chance/honeymart/data/repository/HoneyMartRepositoryImp.kt
  core/data/src/main/java/org/the_chance/honeymart/data/source/remote/mapper/MarketInfo.kt
  core/data/src/main/java/org/the_chance/honeymart/data/source/remote/models/MarketInfoDto.kt
  core/data/src/main/java/org/the_chance/honeymart/data/source/remote/network/HoneyMartService.kt
  core/data/src/main/java/org/the_chance/honeymart/data/source/remote/network/HoneyMartServiceImp.kt
  core/domain/src/main/java/org/the_chance/honeymart/domain/model/MarketInfo.kt
  core/domain/src/main/java/org/the_chance/honeymart/domain/repository/HoneyMartRepository.kt
  core/domain/src/main/java/org/the_chance/honeymart/domain/usecase/GetMarketInfoUseCase.kt
  core/domain/src/main/java/org/the_chance/honeymart/domain/usecase/UpdateMarketStatusUseCase.kt
  design_system/src/main/java/org/the_chance/honymart/ui/theme/Color.kt
  design_system/src/main/res/drawable/icon_map.xml
  design_system/src/main/res/drawable/icon_offline_market.xml
  design_system/src/main/res/drawable/icon_online_market.xml
  design_system/src/main/res/values/strings.xml
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/ProfileInteractionListener.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/ProfileRoute.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/ProfileScreen.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/ProfileUiState.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/ProfileViewModel.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/components/CircleWithText.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/components/StatusChip.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/content/MarketInfoContent.kt
  owner/src/main/java/org/the_chance/honeymart/ui/features/profile/content/PersonalInfoContent.kt
  owner/src/main/java/org/the_chance/honeymart/ui/main/MainScreen.kt
  owner/src/main/java/org/the_chance/honeymart/ui/navigation/MainNavGraph.kt
  owner/src/main/java/org/the_chance/honeymart/ui/navigation/Screen.kt
Labels: feature

#314 add categories
  design_system/src/main/java/org/the_chance/honymart/ui/composables/CategoriesPictures.kt
  design_system/src/main/res/values/strings.xml
  owner/src/main/java/org/the_chance/honeymart/ui/features/category/CategoriesViewModel.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/SeeAllmarkets/MarketInteractionListener.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/SeeAllmarkets/MarketUiEffect.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/SeeAllmarkets/MarketUiState.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/SeeAllmarkets/MarketViewModel.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/SeeAllmarkets/MarketsRoute.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/SeeAllmarkets/MarketsScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/SeeAllmarkets/compoaseable/MarketItem.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/category/MarketScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/home/HomeScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/home/HomeUiState.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/home/HomeViewModel.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/HomeCategoriesItem.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/home/composables/HomeSuccessScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/market/MarketScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/feature/product/ProductsScreen.kt
  user/src/main/java/org/the_chance/honeymart/ui/navigation/HomeNavGraph.kt
Labels: enhancement
